[package]
name = "aether"
version = "0.1.0"
edition = "2024"

[dependencies]
bitcode = { version = "0.6.6", features = ["glam"] }
bytemuck = "1.22.0"
glam = { version = "0.30.1", features = ["bytemuck"] }
